name: Build and Package DSQL for macOS ARM

on:
  workflow_dispatch: # Allow manual triggering
  push:
    tags:
      - "v*" # Run on version tags

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Set up macOS
        run: |
          brew update
          brew install openssl@3 icu4c zip

      - name: Build DSQL
        run: |
          chmod +x scripts/build-dsql.sh
          ./scripts/build-dsql.sh

      - name: Package for Distribution
        run: |
          chmod +x scripts/package.sh
          ./scripts/package.sh

      - name: Test Package
        run: |
          chmod +x scripts/test-packaging.sh
          ./scripts/test-packaging.sh --test-only

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: postgres-dsql
          path: postgres-dsql.zip

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: postgres-dsql.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
